### ISSUE TITLE
Can't start a Virtual Device (Installed Genymotion on Centos7)

### ISSUE THREAD

**Issue by rmulr** [Genymobile/genymotion-kernel#2]
Hey there!

Hope anyone can help here. I stuck with running Genymotion trying for several days now and looking for solutions bot nothing worked out so far.

Now thats what my terminal says when ever i try to start a Virtual Device

```
[root@CentOS-74-64-minimal genymotion]# ./genymotion
Logging activities to file: /root/.Genymobile/genymotion.log
/opt/genymobile/genymotion/player: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/genymobile/genymotion/player)
/opt/genymobile/genymotion/player: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/genymobile/genymotion/libOpenglRender.so.1)
```

libstdc++ is installed 

```
LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
```

But still not working :/

**Comment by fbarthelery** [comment]
I'm sorry to hear that Genymotion doesn't work for you. It seems that your system has a too old version of libstdc++, you should try to update it. I think `CXXABI_1.3.8`  is provided starting the version 4.9.0 of libstdc++

As this Github project is about the Genymotion kernel, a specific component of Genymotion not related to your current issue, I will close this issue.
I suggest that you contact [Genymotion support team](https://www.genymotion.com/contact/), they will provide you a more specific help in the appropriate channel.

**Comment by SnisarOnline** [comment]
Большое спасибо, что не удалил сообщение.
Информация очень помогла мне найти этот пост

https://forums.linuxmint.com/viewtopic.php?t=214288

**Comment by SnisarOnline** [comment]
Many thanks that did not remove the post.
Information very helped me to find this post

https://forums.linuxmint.com/viewtopic.php?t=214288
