### ISSUE TITLE
Provide Chocolatey Package for Genymotion Desktop

### ISSUE THREAD

**Issue by ChargingBulle** [Genymobile/genymotion-kernel#4]
Hi. Sorry if this is the wrong way to contact you.

In large compays Genymotion Desktop needs to be installed on all dev computers.
To help with this task, [Chocolatey](https://chocolatey.org) was created.

Help us deploy your software by [offering an chocolatey package in the community repository](https://github.com/chocolatey/chocolatey-package-requests/issues/570)

**Comment by guillaume-roche** [comment]
Hi @JavaZauber 

For bug reports or feature requests, you can reach us through our contact form available here: https://www.genymotion.com/contact/.

Thanks!
