### ISSUE TITLE
Can't clear logcat buffers 

### ISSUE THREAD

**Issue by 21200** [Genymobile/genymotion-kernel#5]
Hey,

I'm using genymotion desktop and i'm trying to clear the logcat buffers  with the command `adb logcat -b all -c` but it fail to do so , the only way i found to clear it is by turning off and on the android machine 

any idea about the cause of this issue ?

**Comment by guillaume-roche** [comment]
Hi @21200 

For bug reports or feature requests, you can reach us through our contact form available here: https://www.genymotion.com/contact/.

Thanks!
