### ISSUE TITLE
4.4.34 version source sode

### ISSUE THREAD

**Issue by Tolsi** [Genymobile/genymotion-kernel#6]
Can you provide the source code of this kernel used in your virtual phones?

**Comment by Arecardo** [comment]
Hi, I just wonder if you get the source code for the kernel 4.4.34?

**Comment by Tolsi** [comment]
Nope :< You can found Google's original kernel source code, but we can't be sure that Genymotion uses it as is.

**Comment by JulienBolard** [comment]
Here it is :https://github.com/Genymobile/genymotion-kernel/tree/genymotion-android-x86-4.4.34
